AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
        AccessControl: PublicRead
        BucketName: s3-frontend111
        WebsiteConfiguration:
            IndexDocument: index.html
            ErrorDocument: error.html
    DeletionPolicy: Retain
Outputs:
    WebsiteURL:
        Value: !GetAtt
            - S3Bucket
            - WebsiteURL
        Description: URL for website hosted on S3
    S3BuckteSecureURL:
        Value: !Join
            - ''
            -   - 'https://'
                - !GetAtt
                    - S3Bucket
                    - DomainName
        Description: Name of S3 bucket to hold website content
